mod boxes;
mod labels;
mod linefills;
mod lines;
mod polylines;
mod tables;

use pine_ir::{CallSiteId, HirCallArg};

use crate::*;

impl<'a> HistoricalRuntime<'a> {
    pub(crate) fn eval_drawing_call(
        &mut self,
        callee: &str,
        _call_site_id: CallSiteId,
        args: &[HirCallArg],
    ) -> Option<Result<PineValue, RuntimeError>> {
        Some(match callee {
            "label.new" => self.eval_label_new(args),
            "label.set_x" => self.eval_label_set_x(args),
            "label.set_xloc" => self.eval_label_set_xloc(args),
            "label.set_y" => self.eval_label_set_y(args),
            "label.set_xy" => self.eval_label_set_xy(args),
            "label.set_point" => self.eval_label_set_point(args),
            "label.set_yloc" => self.eval_label_set_yloc(args),
            "label.set_text" => self.eval_label_set_text(args),
            "label.set_color" => self.eval_label_set_color(args),
            "label.set_textcolor" => self.eval_label_set_textcolor(args),
            "label.set_style" => self.eval_label_set_style(args),
            "label.set_size" => self.eval_label_set_size(args),
            "label.set_tooltip" => self.eval_label_set_tooltip(args),
            "label.set_textalign" => self.eval_label_set_textalign(args),
            "label.set_text_font_family" => self.eval_label_set_text_font_family(args),
            "label.set_text_formatting" => self.eval_label_set_text_formatting(args),
            "label.delete" => self.eval_label_delete(args),
            "label.copy" => self.eval_label_copy(args),
            "label.get_x" => self.eval_label_get_x(args),
            "label.get_y" => self.eval_label_get_y(args),
            "label.get_text" => self.eval_label_get_text(args),
            "line.new" => self.eval_line_new(args),
            "line.set_first_point" => self.eval_line_set_first_point(args),
            "line.set_x1" => self.eval_line_set_x1(args),
            "line.set_y1" => self.eval_line_set_y1(args),
            "line.set_xy1" => self.eval_line_set_xy1(args),
            "line.set_second_point" => self.eval_line_set_second_point(args),
            "line.set_x2" => self.eval_line_set_x2(args),
            "line.set_y2" => self.eval_line_set_y2(args),
            "line.set_xy2" => self.eval_line_set_xy2(args),
            "line.set_xloc" => self.eval_line_set_xloc(args),
            "line.set_color" => self.eval_line_set_color(args),
            "line.set_width" => self.eval_line_set_width(args),
            "line.set_style" => self.eval_line_set_style(args),
            "line.set_extend" => self.eval_line_set_extend(args),
            "line.delete" => self.eval_line_delete(args),
            "line.copy" => self.eval_line_copy(args),
            "line.get_price" => self.eval_line_get_price(args),
            "line.get_x1" => self.eval_line_get_x1(args),
            "line.get_y1" => self.eval_line_get_y1(args),
            "line.get_x2" => self.eval_line_get_x2(args),
            "line.get_y2" => self.eval_line_get_y2(args),
            "linefill.new" => self.eval_linefill_new(args),
            "linefill.set_color" => self.eval_linefill_set_color(args),
            "linefill.get_line1" => self.eval_linefill_get_line1(args),
            "linefill.get_line2" => self.eval_linefill_get_line2(args),
            "linefill.delete" => self.eval_linefill_delete(args),
            "polyline.new" => self.eval_polyline_new(args),
            "polyline.delete" => self.eval_polyline_delete(args),
            "box.new" => self.eval_box_new(args),
            "box.set_left" => self.eval_box_set_left(args),
            "box.set_top" => self.eval_box_set_top(args),
            "box.set_right" => self.eval_box_set_right(args),
            "box.set_bottom" => self.eval_box_set_bottom(args),
            "box.set_lefttop" => self.eval_box_set_lefttop(args),
            "box.set_top_left_point" => self.eval_box_set_top_left_point(args),
            "box.set_rightbottom" => self.eval_box_set_rightbottom(args),
            "box.set_bottom_right_point" => self.eval_box_set_bottom_right_point(args),
            "box.set_bgcolor" => self.eval_box_set_bgcolor(args),
            "box.set_border_color" => self.eval_box_set_border_color(args),
            "box.set_border_width" => self.eval_box_set_border_width(args),
            "box.set_border_style" => self.eval_box_set_border_style(args),
            "box.set_extend" => self.eval_box_set_extend(args),
            "box.set_xloc" => self.eval_box_set_xloc(args),
            "box.set_text" => self.eval_box_set_text(args),
            "box.set_text_color" => self.eval_box_set_text_color(args),
            "box.set_text_size" => self.eval_box_set_text_size(args),
            "box.set_text_halign" => self.eval_box_set_text_halign(args),
            "box.set_text_valign" => self.eval_box_set_text_valign(args),
            "box.set_text_wrap" => self.eval_box_set_text_wrap(args),
            "box.set_text_font_family" => self.eval_box_set_text_font_family(args),
            "box.set_text_formatting" => self.eval_box_set_text_formatting(args),
            "box.delete" => self.eval_box_delete(args),
            "box.copy" => self.eval_box_copy(args),
            "box.get_top" => self.eval_box_get_top(args),
            "box.get_bottom" => self.eval_box_get_bottom(args),
            "box.get_left" => self.eval_box_get_left(args),
            "box.get_right" => self.eval_box_get_right(args),
            "table.new" => self.eval_table_new(args),
            "table.delete" => self.eval_table_delete(args),
            "table.clear" => self.eval_table_clear(args),
            "table.merge_cells" => self.eval_table_merge_cells(args),
            "table.cell" => self.eval_table_cell(args),
            "table.set_position" => self.eval_table_set_position(args),
            "table.set_bgcolor" => self.eval_table_set_bgcolor(args),
            "table.set_frame_color" => self.eval_table_set_frame_color(args),
            "table.set_frame_width" => self.eval_table_set_frame_width(args),
            "table.set_border_color" => self.eval_table_set_border_color(args),
            "table.set_border_width" => self.eval_table_set_border_width(args),
            "table.cell_set_text" => self.eval_table_cell_set_text(args),
            "table.cell_set_bgcolor" => self.eval_table_cell_set_bgcolor(args),
            "table.cell_set_text_color" => self.eval_table_cell_set_text_color(args),
            "table.cell_set_width" => self.eval_table_cell_set_width(args),
            "table.cell_set_height" => self.eval_table_cell_set_height(args),
            "table.cell_set_text_size" => self.eval_table_cell_set_text_size(args),
            "table.cell_set_text_halign" => self.eval_table_cell_set_text_halign(args),
            "table.cell_set_text_valign" => self.eval_table_cell_set_text_valign(args),
            "table.cell_set_text_wrap" => self.eval_table_cell_set_text_wrap(args),
            "table.cell_set_tooltip" => self.eval_table_cell_set_tooltip(args),
            "table.cell_set_text_font_family" => self.eval_table_cell_set_text_font_family(args),
            "table.cell_set_text_formatting" => self.eval_table_cell_set_text_formatting(args),
            _ => return None,
        })
    }
}
